package com.libraryproject.entity;
// Generated 13 déc. 2015 17:11:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer id;
     private Author author;
     private Category category;
     private String name;
     private BigDecimal price;
     private String description;
     private int stock;
     private String image;
     private Set<Borrowed> borroweds = new HashSet<Borrowed>(0);

    public Book() {
    }

	
    public Book(Author author, Category category, String name, BigDecimal price, String description, int stock, String image) {
        this.author = author;
        this.category = category;
        this.name = name;
        this.price = price;
        this.description = description;
        this.stock = stock;
        this.image = image;
    }
    public Book(Author author, Category category, String name, BigDecimal price, String description, int stock, String image, Set<Borrowed> borroweds) {
       this.author = author;
       this.category = category;
       this.name = name;
       this.price = price;
       this.description = description;
       this.stock = stock;
       this.image = image;
       this.borroweds = borroweds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Author getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Author author) {
        this.author = author;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set<Borrowed> getBorroweds() {
        return this.borroweds;
    }
    
    public void setBorroweds(Set<Borrowed> borroweds) {
        this.borroweds = borroweds;
    }




}


