package com.libraryproject.entity;
// Generated 13 déc. 2015 17:11:41 by Hibernate Tools 4.3.1



/**
 * Borrowed generated by hbm2java
 */
public class Borrowed  implements java.io.Serializable {


     private Integer id;
     private Book book;
     private User user;

    public Borrowed() {
    }

    public Borrowed(Book book, User user) {
       this.book = book;
       this.user = user;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


