package com.libraryproject.entity;
// Generated 3 déc. 2015 18:47:52 by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String surname;
     private String mail;
     private String username;
     private String password;

    public User() {
    }

	
    public User(String mail, String username, String password) {
        this.mail = mail;
        this.username = username;
        this.password = password;
    }
    public User(String name, String surname, String mail, String username, String password) {
       this.name = name;
       this.surname = surname;
       this.mail = mail;
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


