package com.libraryproject.entity;
// Generated 11 déc. 2015 20:36:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String surname;
     private String mail;
     private String username;
     private String password;
     private Set<Borrowed> borroweds = new HashSet<Borrowed>(0);

    public User() {
    }

	
    public User(String mail, String username, String password) {
        this.mail = mail;
        this.username = username;
        this.password = password;
    }
    public User(String name, String surname, String mail, String username, String password, Set<Borrowed> borroweds) {
       this.name = name;
       this.surname = surname;
       this.mail = mail;
       this.username = username;
       this.password = password;
       this.borroweds = borroweds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Borrowed> getBorroweds() {
        return this.borroweds;
    }
    
    public void setBorroweds(Set<Borrowed> borroweds) {
        this.borroweds = borroweds;
    }




}


